owocowe-piatki/home-automation

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- README.md
- backend/README.md
- frontend/.gitignore
- frontend/README.md
- frontend/package.json
- frontend/src/App.jsx
- frontend/src/components/Button.jsx
- frontend/src/components/Button.test.js
- frontend/yarn.lock
```
- Add stylelint for linting styled-components
- Add jest for testing the frontend, with a single simple test
- Add prettier for enforcing formatting, with basic config
- Add a pre-push git hook for testing and linting before pushing
- Organize and improve READMEs
- Run prettier in some components
```
> More frontend linting and testing

- backend/core/schema.py
- backend/core/settings.py
- backend/core/urls.py
- backend/poetry.lock
- backend/pyproject.toml
```
-install drf
-install graphene-django
-configure both 
-use drf auth in graphene
```
> HA-9: Setup GraphQL and REST APIs

- frontend/README.md
- frontend/package.json
```
- Added test:all script that performs prepush tests.
-Added readme and improved husky
```
> HA-39: Added test:all script that performs prepush tests

- backend/apps/users/gql/queries.py
- backend/apps/users/gql/types.py
- backend/core/schema.py
```
- implement UserType and PublicUserType
- add resolvers for current user, and users which have birthday in current month
```
> HA-31: UserTypes and UserQuery for Graphql

- .github/workflows/pull_request_check.yml
- README.md
```
- Changed readme and added gh action
- Fixed regex
```
> HA-40: Add github action to check if PR title meets jira pattern

- backend/apps/users/serializers.py
```
- Add UserSerializer in users app
```
> HA-29: User serializer

- backend/apps/users/rest/urls.py
- backend/apps/users/rest/views.py
- backend/core/urls.py
```
- Add user REST endpoint
- Add rest directory in users app
- Add views file for user REST endpoint
```
> HA-30: User REST endpoint

- frontend/package.json
- frontend/src/Pages/Profile.jsx
- frontend/src/Theme/Components/Error.jsx
- frontend/src/Theme/themes.js
- frontend/src/client.js
- frontend/src/index.jsx
- frontend/yarn.lock
> HA-36: HA-54: Add Apollo GraphQL client

- .dockerignore
- backend/.dockerignore
- backend/apps/mqtt/apps.py
- backend/apps/mqtt/client.py
- backend/core/settings.py
- backend/entrypoint.sh
- backend/example.env
- build.sh
- frontend/.dockerignore
- frontend/webpack/dist.js
```
- Use env vars in settings.py
- Improve dockerignore
- Add RUN_WSGI flag to entrypoint and use it to check if production
- Make the default built docker image run locally
- Add example.env with used env vars (with default local setup)
```
> HA-16: Prepare backend for deployment

- .github/workflows/backend.yml
- .github/workflows/build.yml
- .github/workflows/frontend.yml
```
- Add docker image build and push workflow
- Fixed caching bug in backend workflow
```
> HA-23: HA-51: Deployment workflow and caching bugfix

- Dockerfile
- frontend/package.json
- frontend/webpack/config.js
- frontend/webpack/dev.js
- frontend/webpack/dist.js
```
- Fix the error
- Improve webpack bundle sizes (somehow)
```
> HA-60: Fix frontend crash in production

- .github/workflows/pull_request_check.yml
- README.md
- backend/entrypoint.sh
- frontend/src/client.js
```
- Fix wrong string when testing if running on https
- Add --clear to collectstatic in entrypoint, because it left old bundles
```
> HOTFIX: websocket protocol fix

- Dockerfile
- backend/core/urls.py
- backend/templates/frontend.html
- frontend/package.json
- frontend/src/index.jsx
- frontend/src/sw.js
- frontend/static/manifest.json
- frontend/webpack/dist.js
- frontend/yarn.lock
```
- Add service worker
- Add workbox plugin
- Fix manifest.json
- Serve service worker through backend
```
> HA-68: Set up the frontend as a PWA

- frontend/src/Components/Routing.jsx
- frontend/src/Pages/NotFound.jsx
```
- Added not found page and routing
```
> HA-57: Create a NotFound component and add it to routing

- backend/apps/home/graphql/queries.py
- backend/apps/home/graphql/room_type.py
```
- Filter the appliances based on registered graphql types
```
> HA-69: Fix graphql appliances bug

- backend/appliances/roller/graphql/__init__.py
- backend/appliances/roller/graphql/mutations.py
- backend/appliances/roller/graphql/subscriptions.py
- backend/appliances/roller/graphql/types.py
```
- Add graphql query, mutation, subscription 
```
> HA-47: Add graphql to roller appliance

- frontend/src/Components/Topbar.jsx
> HA-62: Added dropdown menu

- frontend/src/Pages/Lamps/index.jsx
```
Fix the bug where the lamp view would show rooms without lamps
```
> HA-75: Fix the lamp view bug

- backend/appliances/lamp/graphql/__init__.py
- backend/appliances/roller/graphql/__init__.py
- backend/appliances/temp_sensor/graphql/__init__.py
- backend/utils/subscription_signal.py
```
- Subclass subscription event to make serialization 
compatible with django-polymorphic
- Replace the signal everywhere it was used before
```
> HA-78: Fix subscription bug with a monkey patched version of the signal

- frontend/src/Components/Topbar.jsx
- frontend/src/Pages/Dashboard.jsx
```
- Added date and time box
```
> HA-80: Add date and time box in dashboard

- frontend/src/Components/Routing.jsx
- frontend/src/Components/Sidebar.jsx
- frontend/src/Pages/Rollers/Roller.jsx
- frontend/src/Pages/Rollers/Room.jsx
- frontend/src/Pages/Rollers/index.jsx
- frontend/src/Utils/Queries/rollers.js
> HA-73: Create frontend page for rollers

- frontend/src/Components/Sidebar.jsx
- frontend/src/Components/Topbar.jsx
- frontend/src/Pages/Rollers/index.jsx
```
- Fixed bug in dropdown menu
- Fixed bug and typo in rollers
```
> HA-82: Fix dropdown menu bug

- frontend/src/components/Chat/InputBox.jsx
- frontend/src/components/Chat/MessageBox.jsx
```
- Fix imports in chat so that the build can succed
```
> HOTFIX: Fix build errors

- frontend/src/components/Chat/InputBox.jsx
- frontend/src/components/Topbar.jsx
```
- Add min-width to prevent icon shrinking
- Set autocomplete to off in chat input
```
> HA-93: HA-94: Minor frontend bug fixes

- backend/apps/home/graphql/queries.py
- backend/core/settings.py
```
- Add a search query param to appliance list query
```
> HA-88: Create a simple appliance search

- backend/appliances/door/models.py
- backend/appliances/lamp/graphql/mutations.py
- backend/appliances/lamp/models.py
- backend/appliances/roller/graphql/mutations.py
- backend/appliances/roller/models.py
- backend/appliances/socket/graphql/mutations.py
- backend/appliances/socket/models.py
- backend/appliances/temp_sensor/models.py
- backend/appliances/window/models.py
- backend/apps/home/admin.py
- backend/apps/home/apps.py
- backend/apps/home/models.py
- backend/apps/home/signals.py
- backend/apps/home/tests.py
- backend/apps/mqtt/apps.py
- backend/apps/mqtt/client.py
- backend/apps/mqtt/signals.py
- frontend/src/pages/Dashboard.jsx
- frontend/src/pages/Lamps/Lamp.jsx
- frontend/src/pages/Rollers/Roller.jsx
- frontend/src/pages/Sockets/Socket.jsx
- frontend/src/utils/queries/doorsAndWindows.js
```
It is possible for appliance desync, because the server
doesn't know about appliance state at all times.
This PR solves this try introducing appliance and server signals, 
to always be sure that the server knows the appliance state
```
> HA-95: Rework the MQTT topic scheme
